/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reports API and database health */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register/patient": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registers a patient account and signs them in */
        post: operations["AuthController_registerPatient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register/doctor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registers a doctor account (verification pending) and signs them in */
        post: operations["AuthController_registerDoctor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signs a user in */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signs out of the current device */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signs out of every device */
        post: operations["AuthController_logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Changes the signed-in user's password */
        post: operations["AuthController_changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the signed-in user */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/specializations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists the medical specialization catalog, sorted by name */
        get: operations["SpecializationsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the signed-in patient's own profile */
        get: operations["PatientsController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Updates the signed-in patient's own profile */
        patch: operations["PatientsController_updateProfile"];
        trace?: never;
    };
    "/doctors/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the signed-in doctor's own profile */
        get: operations["DoctorsController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Updates the signed-in doctor's own profile */
        patch: operations["DoctorsController_updateProfile"];
        trace?: never;
    };
    "/doctors/me/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the signed-in doctor's time zone, weekly schedule, and upcoming time off */
        get: operations["AvailabilityController_getAvailability"];
        /** Replaces the signed-in doctor's time zone and weekly schedule */
        put: operations["AvailabilityController_saveAvailability"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctors/me/availability/exceptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adds a time-off entry */
        post: operations["AvailabilityController_addTimeOff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctors/me/availability/exceptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Deletes one of the signed-in doctor's own time-off entries */
        delete: operations["AvailabilityController_deleteTimeOff"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctors/{doctorId}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns a doctor's available slots for a date range. Approved doctors are visible to any signed-in user; a doctor who is not yet approved can only see their own slots. */
        get: operations["SlotsController_getSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Searches approved, active doctors with filters, sorting, and pagination */
        get: operations["DiscoveryController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doctors/{doctorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns a doctor's public profile. Approved, active doctors are visible to any signed-in user; a doctor may always view their own profile. */
        get: operations["DiscoveryController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/symptoms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists the symptom catalog, grouped by category and sorted by name */
        get: operations["SymptomsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matching": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Guided symptom matching: scores specializations and ranks approved doctors from selected symptoms and/or free text, using the patient's own profile for the age rule. Nothing is persisted. */
        post: operations["MatchingController_match"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists the signed-in patient's or doctor's own appointments */
        get: operations["AppointmentsController_list"];
        put?: never;
        /** Books an appointment in one of a doctor’s currently available slots */
        post: operations["AppointmentsController_book"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One appointment's details, including its reschedule/cancellation history; participants only */
        get: operations["AppointmentsController_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments/{id}/reschedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reschedules a booked appointment to another available slot with the same doctor */
        post: operations["AppointmentsController_reschedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancels a booked appointment; the doctor must give a reason, the patient may */
        post: operations["AppointmentsController_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists the signed-in user's own notifications, newest first */
        get: operations["NotificationsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user's unread notification count */
        get: operations["NotificationsController_unreadCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Marks one of the signed-in user's own notifications as read */
        post: operations["NotificationsController_markRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Marks all of the signed-in user's notifications as read */
        post: operations["NotificationsController_markAllRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultations/{appointmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The appointment's consultation workspace; participants only */
        get: operations["ConsultationsController_getWorkspace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultations/{appointmentId}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Joins the consultation, from 15 minutes before it starts until 30 minutes after it ends */
        post: operations["ConsultationsController_join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultations/{appointmentId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Starts the consultation once the patient has joined; doctor only */
        post: operations["ConsultationsController_start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultations/{appointmentId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Completes the consultation once a patient summary is written; doctor only */
        post: operations["ConsultationsController_complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultations/{appointmentId}/note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replaces the consultation's note; doctor only, while the session is JOINED or IN_PROGRESS */
        put: operations["ConsultationRecordsController_saveNote"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultations/{appointmentId}/prescriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adds a prescription to the consultation; doctor only */
        post: operations["ConsultationRecordsController_addPrescription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultations/{appointmentId}/prescriptions/{prescriptionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Removes a prescription; doctor only */
        delete: operations["ConsultationRecordsController_deletePrescription"];
        options?: never;
        head?: never;
        /** Updates one field or more of a prescription; doctor only */
        patch: operations["ConsultationRecordsController_updatePrescription"];
        trace?: never;
    };
    "/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists the signed-in patient's completed consultations, newest first */
        get: operations["RecordsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records/{appointmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One of the signed-in patient's own completed consultation records */
        get: operations["RecordsController_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patientId}/record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A patient's record, for a doctor with a booked or completed appointment with them */
        get: operations["RecordsController_doctorViewPatient"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterPatientDto: {
            email: string;
            /** @description 10-128 characters, must not equal the email */
            password: string;
            firstName: string;
            lastName: string;
        };
        AuthSessionResponseDto: {
            id: string;
            email: string;
            /** @enum {string} */
            role: "PATIENT" | "DOCTOR" | "ADMIN";
        };
        RegisterDoctorDto: {
            email: string;
            /** @description 10-128 characters, must not equal the email */
            password: string;
            firstName: string;
            lastName: string;
            /** @description At least one specialization ID from the catalog */
            specializationIds: string[];
            /** @description 4-32 letters, digits, or dashes */
            licenseNumber: string;
        };
        LoginDto: {
            email: string;
            password: string;
        };
        ChangePasswordDto: {
            currentPassword: string;
            /** @description 10-128 characters, must not equal the email */
            newPassword: string;
        };
        CurrentUserResponseDto: {
            id: string;
            email: string;
            /** @enum {string} */
            role: "PATIENT" | "DOCTOR" | "ADMIN";
            /** @enum {string} */
            status: "ACTIVE" | "SUSPENDED" | "DEACTIVATED";
            displayName: string;
            /** @description Present only for PATIENT */
            profileComplete?: boolean;
            /**
             * @description Present only for DOCTOR
             * @enum {string}
             */
            verificationStatus?: "PENDING" | "APPROVED" | "REJECTED";
        };
        SpecializationResponseDto: {
            id: string;
            slug: string;
            name: string;
            description: string;
        };
        PatientProfileResponseDto: {
            firstName: string;
            lastName: string;
            birthDate: string | null;
            weightKg: number | null;
            heightCm: number | null;
            phone: string | null;
            emergencyContactName: string | null;
            emergencyContactPhone: string | null;
            medicalConditions: string | null;
            allergies: string | null;
            currentMedications: string | null;
            profileComplete: boolean;
        };
        UpdatePatientProfileDto: {
            firstName?: string;
            lastName?: string;
            /** @example 1990-01-31 */
            birthDate?: string;
            weightKg?: number;
            heightCm?: number;
            phone?: string;
            emergencyContactName?: string;
            emergencyContactPhone?: string;
            medicalConditions?: string;
            allergies?: string;
            currentMedications?: string;
        };
        SpecializationSummaryDto: {
            id: string;
            name: string;
        };
        DoctorProfileResponseDto: {
            firstName: string;
            lastName: string;
            bio: string | null;
            yearsOfExperience: number | null;
            licenseNumber: string;
            consultationMinutes: number;
            /** @enum {string} */
            verificationStatus: "PENDING" | "APPROVED" | "REJECTED";
            reviewNote: string | null;
            specializations: components["schemas"]["SpecializationSummaryDto"][];
        };
        UpdateDoctorProfileDto: {
            firstName?: string;
            lastName?: string;
            bio?: string;
            yearsOfExperience?: number;
            /** @description 4-32 letters, digits, or dashes */
            licenseNumber?: string;
            /** @enum {number} */
            consultationMinutes?: 15 | 20 | 30 | 45 | 60;
            /** @description Replaces the full set of specializations; at least one is required when provided */
            specializationIds?: string[];
        };
        AvailabilityRuleResponseDto: {
            weekday: number;
            startMinute: number;
            endMinute: number;
        };
        TimeOffResponseDto: {
            id: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            reason: string | null;
        };
        AvailabilityResponseDto: {
            /** @description IANA time zone */
            timezone: string;
            rules: components["schemas"]["AvailabilityRuleResponseDto"][];
            /** @description Time off that ends in the future */
            timeOff: components["schemas"]["TimeOffResponseDto"][];
        };
        AvailabilityRuleDto: {
            /** @description ISO weekday: Monday = 1, Sunday = 7 */
            weekday: number;
            /** @description Minutes since local midnight */
            startMinute: number;
            /** @description Minutes since local midnight */
            endMinute: number;
        };
        SaveAvailabilityDto: {
            /** @description IANA time zone, e.g. Asia/Manila */
            timezone: string;
            rules: components["schemas"]["AvailabilityRuleDto"][];
        };
        CreateTimeOffDto: {
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            reason?: string;
        };
        SlotResponseDto: {
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
        };
        DoctorSearchResultDto: {
            id: string;
            displayName: string;
            specializations: components["schemas"]["SpecializationSummaryDto"][];
            bioExcerpt: string | null;
            yearsOfExperience: number | null;
            consultationMinutes: number;
            /** Format: date-time */
            nextAvailableSlot: string | null;
        };
        DoctorSearchResponseDto: {
            items: components["schemas"]["DoctorSearchResultDto"][];
            total: number;
            page: number;
            pageSize: number;
        };
        PublicSpecializationDto: {
            id: string;
            slug: string;
            name: string;
            description: string;
        };
        PublicDoctorProfileDto: {
            id: string;
            displayName: string;
            bio: string | null;
            specializations: components["schemas"]["PublicSpecializationDto"][];
            yearsOfExperience: number | null;
            consultationMinutes: number;
            timezone: string;
        };
        SymptomSummaryDto: {
            id: string;
            slug: string;
            name: string;
            category: string;
            isRedFlag: boolean;
        };
        SymptomCategoryDto: {
            category: string;
            symptoms: components["schemas"]["SymptomSummaryDto"][];
        };
        MatchingRequestDto: {
            /** @description Symptom IDs from the catalog */
            symptomIds?: string[];
            descriptionText?: string;
        };
        RedFlagDto: {
            symptomId: string;
            symptomName: string;
        };
        MatchedSymptomDto: {
            symptomId: string;
            symptomName: string;
            /** @enum {string} */
            source: "selected" | "described";
        };
        MatchReasonDto: {
            symptomId: string | null;
            symptomName: string | null;
            specializationId: string;
            specializationName: string;
            weight: number;
            /** @enum {string} */
            source: "selected" | "described" | "age" | "default";
        };
        SpecializationMatchDto: {
            specializationId: string;
            specializationName: string;
            score: number;
            reasons: components["schemas"]["MatchReasonDto"][];
        };
        DoctorMatchDto: {
            doctorId: string;
            displayName: string;
            specializationId: string;
            score: number;
            reasons: components["schemas"]["MatchReasonDto"][];
            /** Format: date-time */
            nextAvailableSlot: string | null;
        };
        MatchingResponseDto: {
            urgent: boolean;
            emergencyMessage: string | null;
            redFlags: components["schemas"]["RedFlagDto"][];
            matchedSymptoms: components["schemas"]["MatchedSymptomDto"][];
            specializations: components["schemas"]["SpecializationMatchDto"][];
            doctors: components["schemas"]["DoctorMatchDto"][];
            /** @description True when the age rule could not run because the patient has no birthday on file */
            ageUnknown: boolean;
        };
        CreateAppointmentDto: {
            doctorId: string;
            /**
             * Format: date-time
             * @description The slot start, as returned by the slots endpoint
             */
            startsAt: string;
            reason: string;
            /** @description Symptom IDs carried over from guided matching */
            symptomIds?: string[];
        };
        AppointmentDoctorSummaryDto: {
            id: string;
            displayName: string;
            specializations: components["schemas"]["SpecializationSummaryDto"][];
        };
        AppointmentPatientSummaryDto: {
            id: string;
            displayName: string;
            age: number | null;
        };
        AppointmentSymptomSummaryDto: {
            id: string;
            name: string;
        };
        AppointmentResponseDto: {
            id: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            /** @enum {string} */
            status: "BOOKED" | "CANCELLED" | "COMPLETED";
            reason: string;
            doctor: components["schemas"]["AppointmentDoctorSummaryDto"];
            patient: components["schemas"]["AppointmentPatientSummaryDto"];
            symptoms: components["schemas"]["AppointmentSymptomSummaryDto"][];
            /** Format: date-time */
            cancelledAt: string | null;
            cancellationReason: string | null;
            /** @enum {string|null} */
            cancelledByRole: "PATIENT" | "DOCTOR" | null;
            /** @description The appointment this one replaced, if any */
            rescheduledFromId?: string | null;
        };
        ErrorResponseDto: {
            statusCode: number;
            error: string;
            message: string;
            requestId: string;
            /** @description Stable machine-readable code for a business-rule violation, e.g. SLOT_UNAVAILABLE. */
            code?: string;
            /** @description Extra structured detail for some codes, e.g. the appointments a schedule change would orphan. */
            details?: {
                [key: string]: unknown;
            };
            /** @description Field-indexed validation errors, when the request failed validation. */
            errors?: {
                [key: string]: unknown;
            }[];
        };
        AppointmentListResponseDto: {
            items: components["schemas"]["AppointmentResponseDto"][];
            total: number;
            page: number;
            pageSize: number;
        };
        AppointmentHistoryEntryDto: {
            id: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            /** @enum {string} */
            status: "BOOKED" | "CANCELLED" | "COMPLETED";
            /** Format: date-time */
            cancelledAt: string | null;
            cancellationReason: string | null;
        };
        AppointmentDetailResponseDto: {
            id: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            /** @enum {string} */
            status: "BOOKED" | "CANCELLED" | "COMPLETED";
            reason: string;
            doctor: components["schemas"]["AppointmentDoctorSummaryDto"];
            patient: components["schemas"]["AppointmentPatientSummaryDto"];
            symptoms: components["schemas"]["AppointmentSymptomSummaryDto"][];
            /** Format: date-time */
            cancelledAt: string | null;
            cancellationReason: string | null;
            /** @enum {string|null} */
            cancelledByRole: "PATIENT" | "DOCTOR" | null;
            /** @description The appointment this one replaced, if any */
            rescheduledFromId?: string | null;
            /** @description The appointment this one was rescheduled into, if any */
            rescheduledToId?: string | null;
            /** @description The full reschedule/cancellation chain, chronological */
            history: components["schemas"]["AppointmentHistoryEntryDto"][];
        };
        RescheduleAppointmentDto: {
            /**
             * Format: date-time
             * @description The new slot start, with the same doctor
             */
            startsAt: string;
        };
        CancelAppointmentDto: {
            reason?: string;
        };
        NotificationResponseDto: {
            id: string;
            /** @enum {string} */
            type: "APPOINTMENT_BOOKED" | "BOOKING_CONFIRMED" | "APPOINTMENT_RESCHEDULED" | "RESCHEDULE_CONFIRMED" | "APPOINTMENT_CANCELLED" | "REMINDER_24H" | "REMINDER_1H" | "CONSULTATION_SUMMARY_AVAILABLE";
            title: string;
            body: string;
            /** @description Structured event data (startsAt, previousStartsAt, counterpartName, reason) for the viewer to format. */
            data: {
                [key: string]: unknown;
            } | null;
            /** @description A link to the appointment in the recipient's role area */
            link: string | null;
            appointmentId: string | null;
            /** Format: date-time */
            readAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        NotificationListResponseDto: {
            items: components["schemas"]["NotificationResponseDto"][];
            total: number;
            page: number;
            pageSize: number;
            unreadCount: number;
        };
        UnreadCountResponseDto: {
            unreadCount: number;
        };
        ConsultationSessionStateDto: {
            /** @enum {string} */
            state: "SCHEDULED" | "JOINED" | "IN_PROGRESS" | "COMPLETED";
            /** Format: date-time */
            patientJoinedAt: string | null;
            /** Format: date-time */
            doctorJoinedAt: string | null;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            completedAt: string | null;
        };
        ConsultationPatientSummaryDto: {
            age: number | null;
            medicalConditions: string | null;
            allergies: string | null;
            currentMedications: string | null;
        };
        ConsultationNoteDto: {
            findings: string | null;
            assessment: string | null;
            plan: string | null;
            patientSummary: string | null;
            /** Format: date-time */
            updatedAt: string;
        };
        PrescriptionResponseDto: {
            id: string;
            medication: string;
            dosage: string;
            frequency: string;
            duration: string;
            instructions: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ConsultationWorkspaceResponseDto: {
            appointmentId: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            reason: string;
            doctor: components["schemas"]["AppointmentDoctorSummaryDto"];
            patient: components["schemas"]["AppointmentPatientSummaryDto"];
            symptoms: components["schemas"]["AppointmentSymptomSummaryDto"][];
            session: components["schemas"]["ConsultationSessionStateDto"];
            patientMedicalSummary?: components["schemas"]["ConsultationPatientSummaryDto"] | null;
            note?: components["schemas"]["ConsultationNoteDto"] | null;
            prescriptions?: components["schemas"]["PrescriptionResponseDto"][];
        };
        SaveConsultationNoteDto: {
            findings?: string;
            assessment?: string;
            plan?: string;
            patientSummary?: string;
        };
        CreatePrescriptionDto: {
            medication: string;
            dosage: string;
            frequency: string;
            duration: string;
            instructions?: string;
        };
        UpdatePrescriptionDto: {
            medication?: string;
            dosage?: string;
            frequency?: string;
            duration?: string;
            instructions?: string;
        };
        RecordListItemDto: {
            appointmentId: string;
            /** Format: date-time */
            startsAt: string;
            doctor: components["schemas"]["AppointmentDoctorSummaryDto"];
            patientSummary: string | null;
        };
        RecordListResponseDto: {
            items: components["schemas"]["RecordListItemDto"][];
            total: number;
            page: number;
            pageSize: number;
        };
        RecordDetailResponseDto: {
            appointmentId: string;
            /** Format: date-time */
            startsAt: string;
            doctor: components["schemas"]["AppointmentDoctorSummaryDto"];
            note: components["schemas"]["ConsultationNoteDto"] | null;
            prescriptions: components["schemas"]["PrescriptionResponseDto"][];
        };
        DoctorPatientAppointmentDto: {
            id: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            /** @enum {string} */
            status: "BOOKED" | "CANCELLED" | "COMPLETED";
            reason: string;
        };
        DoctorPatientRecordResponseDto: {
            patientId: string;
            firstName: string;
            lastName: string;
            age: number | null;
            medicalConditions: string | null;
            allergies: string | null;
            currentMedications: string | null;
            appointmentsWithDoctor: components["schemas"]["DoctorPatientAppointmentDto"][];
            completedConsultations: components["schemas"]["RecordListItemDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API and database are healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The database is unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_registerPatient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterPatientDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponseDto"];
                };
            };
        };
    };
    AuthController_registerDoctor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDoctorDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponseDto"];
                };
            };
        };
    };
    SpecializationsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecializationResponseDto"][];
                };
            };
        };
    };
    PatientsController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientProfileResponseDto"];
                };
            };
        };
    };
    PatientsController_updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePatientProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientProfileResponseDto"];
                };
            };
        };
    };
    DoctorsController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorProfileResponseDto"];
                };
            };
        };
    };
    DoctorsController_updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDoctorProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorProfileResponseDto"];
                };
            };
        };
    };
    AvailabilityController_getAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityResponseDto"];
                };
            };
        };
    };
    AvailabilityController_saveAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveAvailabilityDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityResponseDto"];
                };
            };
        };
    };
    AvailabilityController_addTimeOff: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTimeOffDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeOffResponseDto"];
                };
            };
        };
    };
    AvailabilityController_deleteTimeOff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SlotsController_getSlots: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path: {
                doctorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotResponseDto"][];
                };
            };
        };
    };
    DiscoveryController_search: {
        parameters: {
            query?: {
                /** @description Matches doctor name or specialization name, case-insensitive */
                q?: string;
                /** @description Specialization slug, e.g. cardiology */
                specialization?: string;
                availableFrom?: string;
                availableTo?: string;
                sort?: "next" | "name" | "experience";
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorSearchResponseDto"];
                };
            };
        };
    };
    DiscoveryController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doctorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicDoctorProfileDto"];
                };
            };
        };
    };
    SymptomsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymptomCategoryDto"][];
                };
            };
        };
    };
    MatchingController_match: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchingRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchingResponseDto"];
                };
            };
        };
    };
    AppointmentsController_list: {
        parameters: {
            query: {
                scope: "upcoming" | "past";
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentListResponseDto"];
                };
            };
        };
    };
    AppointmentsController_book: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAppointmentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponseDto"];
                };
            };
            /** @description A business rule was violated (see the code field) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AppointmentsController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentDetailResponseDto"];
                };
            };
        };
    };
    AppointmentsController_reschedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RescheduleAppointmentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponseDto"];
                };
            };
            /** @description A business rule was violated (see the code field) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AppointmentsController_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelAppointmentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentResponseDto"];
                };
            };
            /** @description A business rule was violated (see the code field) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    NotificationsController_list: {
        parameters: {
            query?: {
                /** @description When true, only unread notifications are returned */
                unreadOnly?: boolean;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationListResponseDto"];
                };
            };
        };
    };
    NotificationsController_unreadCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnreadCountResponseDto"];
                };
            };
        };
    };
    NotificationsController_markRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponseDto"];
                };
            };
        };
    };
    NotificationsController_markAllRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConsultationsController_getWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultationWorkspaceResponseDto"];
                };
            };
            /** @description The appointment is not active */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ConsultationsController_join: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultationSessionStateDto"];
                };
            };
            /** @description A business rule was violated (see the code field) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ConsultationsController_start: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultationSessionStateDto"];
                };
            };
            /** @description A business rule was violated (see the code field) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ConsultationsController_complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultationSessionStateDto"];
                };
            };
            /** @description A business rule was violated (see the code field) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ConsultationRecordsController_saveNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointmentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveConsultationNoteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultationNoteDto"];
                };
            };
            /** @description A business rule was violated (see the code field) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ConsultationRecordsController_addPrescription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointmentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePrescriptionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrescriptionResponseDto"];
                };
            };
            /** @description A business rule was violated (see the code field) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ConsultationRecordsController_deletePrescription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointmentId: string;
                prescriptionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A business rule was violated (see the code field) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ConsultationRecordsController_updatePrescription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointmentId: string;
                prescriptionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePrescriptionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrescriptionResponseDto"];
                };
            };
            /** @description A business rule was violated (see the code field) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    RecordsController_list: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordListResponseDto"];
                };
            };
        };
    };
    RecordsController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordDetailResponseDto"];
                };
            };
        };
    };
    RecordsController_doctorViewPatient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorPatientRecordResponseDto"];
                };
            };
        };
    };
}
